### ISSUE TITLE
Refactoring the "close_last_tab" setting

### ISSUE THREAD

**Issue by ReanGD** [simonzack/urxvt-tabbed#16]
What do you think about refactoring the "close_last_tab" setting, I would like:
- rename "new" to "open_new_tab"
- rename "close" to "close_application"
- remove "blank" - I don't understand why someone needs a blank window, the other two options should cover all cases

**Comment by simonzack** [comment]
Sure thing, good ideas!

I forgot this setting even existed haha. It's been a while. Thanks for doing so much on this project!

**Comment by ReanGD** [comment]
I'm just trying to make a perfect terminal for myself)
