### ISSUE TITLE
GUI for configuring

### ISSUE THREAD

**Issue by ReanGD** [simonzack/urxvt-tabbed#17]
What do you think about adding a settings window. I would like to add an icon https://en.wikipedia.org/wiki/Hamburger_button with menu items "preferences" and "quit" (the list may be expanded in the future). For the "preferences" element I will try to make a GUI for configuring. Does this conflict with your project plans?

**Comment by simonzack** [comment]
Hmm I'm trying to make this project really simple. The current settings file is very small, and can be easily configured.

I personally prefer config files over GUI, per my experience with Windows GUI often being horrible to use and find things (e.g. Visual Studio).

Perhaps it makes sense if the GUI is well designed and there are just too many options.

**Comment by ReanGD** [comment]
Okay
